import { useRef, useState } from 'react';
import { apiFetch, resolveDjangoUrl, toFormData } from '../api/client';
import Alert from '../components/Alert';

function writeAscii(view, offset, text){for(let i=0;i<text.length;i+=1)view.setUint8(offset+i,text.charCodeAt(i));}
function mergePcm(chunks){const length=chunks.reduce((sum,c)=>sum+c.length,0);const merged=new Float32Array(length);let offset=0;chunks.forEach(c=>{merged.set(c,offset);offset+=c.length;});return merged;}
function resampleTo16k(input,sourceRate){if(sourceRate===16000)return new Float32Array(input);const outputLength=Math.max(1,Math.round(input.length*16000/sourceRate));const output=new Float32Array(outputLength);for(let i=0;i<outputLength;i+=1){const pos=i*sourceRate/16000;const left=Math.floor(pos);const right=Math.min(left+1,input.length-1);const fraction=pos-left;output[i]=input[left]*(1-fraction)+input[right]*fraction;}return output;}
function encodeWav(samples,sampleRate=16000){const buffer=new ArrayBuffer(44+samples.length*2);const view=new DataView(buffer);writeAscii(view,0,'RIFF');view.setUint32(4,36+samples.length*2,true);writeAscii(view,8,'WAVE');writeAscii(view,12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);writeAscii(view,36,'data');view.setUint32(40,samples.length*2,true);let offset=44;samples.forEach(sample=>{const clipped=Math.max(-1,Math.min(1,sample));view.setInt16(offset,clipped<0?clipped*0x8000:clipped*0x7fff,true);offset+=2;});return new Blob([view],{type:'audio/wav'});}

export default function MultimodalPage(){
  const[status,setStatus]=useState('Django를 통해 FastAPI AI 서버 상태를 확인할 수 있습니다.');const[error,setError]=useState('');
  const[caption,setCaption]=useState(null);const[captionPreview,setCaptionPreview]=useState('');const[generated,setGenerated]=useState(null);const[stt,setStt]=useState('');
  const[prompt,setPrompt]=useState('');const[ttsText,setTtsText]=useState('');const[recording,setRecording]=useState(false);
  const captionAudio=useRef(null);const ttsAudio=useRef(null);const recorder=useRef({stream:null,ctx:null,source:null,processor:null,gain:null,chunks:[]});
  const showError=e=>{setError(e.message);setStatus('처리 중 오류가 발생했습니다.');};
  const health=async()=>{setError('');try{const d=await apiFetch('/api/ai/health/');setStatus(`FastAPI 상태: ${d.status} / MySQL: ${d.database}`);}catch(e){showError(e)}};
  const submitCaption=async e=>{e.preventDefault();setError('');setStatus('이미지를 분석하고 있습니다.');const file=e.currentTarget.file.files[0];if(!file)return;try{const fd=new FormData();fd.append('file',file);const d=await apiFetch('/api/ai/caption/',{method:'POST',body:fd});setCaption(d);setStatus('이미지 캡셔닝이 완료되었습니다.');}catch(err){showError(err)}};
  const submitGenerate=async e=>{e.preventDefault();setError('');setStatus('Stable Diffusion 이미지 생성 중입니다.');const fd=new FormData(e.currentTarget);try{const d=await apiFetch('/api/ai/generate/',{method:'POST',body:fd});setGenerated(d);setStatus('이미지 생성이 완료되었습니다.');}catch(err){showError(err)}};
  const requestTts=async(text,audioRef)=>{if(!text.trim())throw new Error('TTS로 읽을 문장을 입력하세요.');const d=await apiFetch('/api/ai/tts/',{method:'POST',body:toFormData({text})});audioRef.current.src=resolveDjangoUrl(d.audio_url)+`?t=${Date.now()}`;await audioRef.current.play();};
  const release=async()=>{const r=recorder.current;if(r.processor){r.processor.onaudioprocess=null;r.processor.disconnect();}if(r.source)r.source.disconnect();if(r.gain)r.gain.disconnect();if(r.stream)r.stream.getTracks().forEach(t=>t.stop());if(r.ctx&&r.ctx.state!=='closed')await r.ctx.close();recorder.current={stream:null,ctx:null,source:null,processor:null,gain:null,chunks:[]};};
  const toggleRecord=async()=>{setError('');if(!recording){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const ctx=new(window.AudioContext||window.webkitAudioContext)();const source=ctx.createMediaStreamSource(stream);const processor=ctx.createScriptProcessor(4096,1,1);const gain=ctx.createGain();gain.gain.value=0;const chunks=[];processor.onaudioprocess=e=>chunks.push(new Float32Array(e.inputBuffer.getChannelData(0)));source.connect(processor);processor.connect(gain);gain.connect(ctx.destination);recorder.current={stream,ctx,source,processor,gain,chunks};setRecording(true);setStatus('녹음 중입니다. 다시 누르면 녹음을 종료하고 STT를 수행합니다.');}catch(e){showError(new Error(`마이크 사용 실패: ${e.message}`));}return;}const r=recorder.current;const sourceRate=r.ctx.sampleRate;setRecording(false);try{const wav=encodeWav(resampleTo16k(mergePcm(r.chunks),sourceRate),16000);await release();const fd=new FormData();fd.append('file',wav,'recording.wav');setStatus('Whisper STT 변환 중입니다.');const d=await apiFetch('/api/ai/stt/',{method:'POST',body:fd});setStt(d.text||'');setPrompt(d.text||'');setStatus('STT 변환이 완료되었습니다. 변환 텍스트를 이미지 생성 프롬프트에 적용했습니다.');}catch(e){await release();showError(e)}};
  return <><div className="d-flex justify-content-between align-items-center mb-3"><div><h2 className="mb-1">멀티모달 AI</h2><div className="text-muted">React → Django → FastAPI 방식으로 캡셔닝·이미지 생성·STT·TTS를 실행합니다.</div></div><button className="btn btn-outline-secondary" onClick={health}>AI 서버 상태</button></div><Alert type="info">{status}</Alert><Alert type="danger">{error}</Alert><div className="row g-4">
    <div className="col-lg-6"><div className="card shadow-sm h-100"><div className="card-body"><h4>이미지 캡셔닝</h4><form onSubmit={submitCaption}><input name="file" type="file" accept="image/*" className="form-control mb-3" required onChange={e=>{const f=e.target.files[0];setCaptionPreview(f?URL.createObjectURL(f):'')}}/>{captionPreview&&<img className="img-fluid rounded border mb-3 preview-image" src={captionPreview} alt="미리보기"/>}<button className="btn btn-primary">이미지 분석</button></form>{caption&&<div className="mt-3"><div><strong>영문:</strong> {caption.caption_en}</div><div className="mt-2"><strong>한국어:</strong> {caption.caption_ko}</div><button className="btn btn-outline-primary btn-sm mt-3" onClick={()=>requestTts(caption.caption_ko,captionAudio).catch(showError)}>한국어 캡션 듣기</button><audio ref={captionAudio} controls className="w-100 mt-2" /></div>}</div></div></div>
    <div className="col-lg-6"><div className="card shadow-sm h-100"><div className="card-body"><h4>음성 프롬프트 STT</h4><button className={`btn ${recording?'btn-danger':'btn-outline-primary'} mb-3`} onClick={toggleRecord}>{recording?'⏹ 녹음 종료 및 STT':'🎤 음성 프롬프트 녹음'}</button><textarea className="form-control" rows="5" value={stt} readOnly placeholder="STT 결과가 여기에 표시됩니다."/></div></div></div>
    <div className="col-lg-7"><div className="card shadow-sm"><div className="card-body"><h4>Stable Diffusion 이미지 생성</h4><form onSubmit={submitGenerate}><label className="form-label">프롬프트</label><textarea name="prompt" id="prompt" className="form-control mb-3" rows="4" value={prompt} onChange={e=>setPrompt(e.target.value)} required/><label className="form-label">Negative Prompt</label><input name="negative_prompt" className="form-control mb-3" defaultValue="blurry, low quality, distorted, watermark, text"/><div className="row"><div className="col-md-4"><label className="form-label">Steps</label><input name="steps" type="number" min="5" max="60" className="form-control" defaultValue="40"/></div><div className="col-md-4"><label className="form-label">Guidance Scale</label><input name="guidance_scale" type="number" step="0.5" min="1" max="20" className="form-control" defaultValue="8"/></div><div className="col-md-4"><label className="form-label">Seed</label><input name="seed" type="number" className="form-control" placeholder="자동"/></div></div><button className="btn btn-primary mt-3">이미지 생성</button></form>{generated&&<div className="mt-4"><img className="img-fluid rounded border generated-image" src={resolveDjangoUrl(generated.image_url)+`?t=${Date.now()}`} alt="생성 결과"/><div className="small text-muted mt-2">Seed: {generated.seed}</div><div className="small"><strong>적용 프롬프트:</strong> {generated.prompt_used||generated.prompt_english||generated.prompt_original}</div></div>}</div></div></div>
    <div className="col-lg-5"><div className="card shadow-sm"><div className="card-body"><h4>텍스트 음성 변환 TTS</h4><textarea className="form-control mb-3" rows="7" value={ttsText} onChange={e=>setTtsText(e.target.value)} placeholder="음성으로 들을 한국어 문장을 입력하세요."/><button className="btn btn-primary" onClick={()=>requestTts(ttsText,ttsAudio).catch(showError)}>TTS 재생</button><audio ref={ttsAudio} controls className="w-100 mt-3"/></div></div></div>
  </div></>;
}
